name: flutter_dummyapi

packages:
  - packages/**
  - "*"

scripts:
  build-runner:
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build runner

  pub-get:
    run: melos exec -- flutter pub get
    description: Get all packages' dependencies

  analyze:
    run: melos exec -- flutter analyze .
    description: Analyze all packages
