name: flutter_dummyapi
description: A flutter app showing posts.

publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  base:
    path: packages/base
  config:
    path: packages/config
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  home:
    path: packages/home
  network:
    path: packages/network
  post:
    path: packages/post
  user:
    path: packages/user

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
