name: network
description: Network module.
version: 0.0.7

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  config:
    path: ../config
  connectivity_plus: ^2.2.1
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.3
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.8

flutter:
