name: base
description: Base module.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.20.1

flutter: null
