name: post
description: Post package.
version: 0.0.3

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  base:
    path: ../base
  cached_network_image: ^3.2.0
  config:
    path: ../config
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  meta: ^1.7.0
  network:
    path: ../network
  provider: ^6.0.2
  shared_widgets:
    path: ../shared_widgets
  user:
    path: ../user

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
