name: user
description: User package.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5

flutter: null
