name: config
description: Config module.
version: 0.0.3

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3

flutter: null
