name: home
description: Home package.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  base:
    path: ../base
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.3
  post:
    path: ../post
  user:
    path: ../user

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
